language: objective-c
osx_image: xcode8.3

env:
  global:
    - FRAMEWORK_NAME=CVGenericDataSource
    - LANG=en_US.UTF-8
    - PROJECT="CVGenericDataSource.xcodeproj"
    - IOS_SCHEME="CVGenericDataSourceTests"
    - IOS_SDK=iphonesimulator10.3

  matrix:         
    - DESTINATION="OS=10.3,name=iPhone 5" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 5s" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 6" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 6 Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 6s"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 6s Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 7"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPhone 7 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"      
    - DESTINATION="OS=10.3,name=iPad Air"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPad Air 2"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPad Pro (9.7-inch)"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3,name=iPad Pro (12.9-inch)"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
  - set -o pipefail

  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      travis_retry xcodebuild build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi

  - if [ $BUILD_EXAMPLE == "YES" ]; then
      travis_retry xcodebuild build analyze -project Example/CVGenericDataSourceExample.xcodeproj -scheme CVGenericDataSourceExample -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi

  - if [ $POD_LINT == "YES" ]; then
        pod lib lint;
    fi
deploy:
  provider: releases
  api_key:
    secure: t2hXwN5mQwnwq1JGKy+XhL1Bfjaw/ux6jDaRmqQBGXVk0JE7s4SD5w1cmhoXKa1/3XQKaY1cZ3HihMs7cbPtEHU46hnnPtJVDvPFGDqhR1ArprttEKFhj79AtFGDuSLxxzj8bt+/TdzdsZvooop06GaijaBM2LQJ1U70mQ5GuxZTOjvYCrUb3lqJ8w2uVQqil1sCtq6+sKWZ4P51Pg/LhV6qp9tPcN1GlX8KHuxjfons6cqxmf+B0GWIP4/GclXxt8Cnlqn+JaMwcEl4yNb5bqnIVXObS9Ya9dpoWjj8dxGofssjqOmjarh7Xm8xYOsUeuDMiio+ZjanA4//PwzrfXKTUbjYqsD/mCXrOCnoI19ZtJbZ6mdSScQcBBwbuOtFEOuiLx/sYmi4hDM7A2AgAidR0LOdO4obYahTb5ilzoIzc2WnyJYLmeES7DcJU0yT7u/R3ID2L5HGhVGH7htBtzCb8vd5GurK+zeXYR4Xu7SWGyZa9oX0ERZnQxVpvT3KCluoM/oMRBwtT6VHzlXqpQsNSEf7+gciT5gzAeMfHKb136//jy/ckGBhbXCGRtuSxSo1ocHDm2nQFAizpQR+Z4tpOYn5lfrT/NWpNw83uSGJPA5V8+YOid7NqT865rmSTalJVwIEVQS7gt1TC5uCYT+ykGZK03qx8fpL2ylwdvk=
  file: CVGenericDataSource.framework.zip
  skip_cleanup: true
  on:
    repo: mittenimraum/CVGenericDataSource
    tags: true